### ISSUE TITLE
What does the extension do?

### ISSUE THREAD

**Issue by ilyaigpetrov** [Etheryte/right-click-opens-link-in-a-background-tab#1]
It's not clear what your extension does.
Please, provide gif/video or more screenshots.

> [...]makes right clicking on links open them in a new background tab.

Extensions in MV2 had background tab but, I guess, this is not what you mean.
After some contemplation I think your extension opens new tab in passive state (not activated) but this is what `Ctrl + click` do without any extensions, so I'm not sure, what you meant.

**Comment by Etheryte** [comment]
@ilyaigpetrov Essentially this extension is `Cmd + click` / `Ctrl + click` / middle mouse click on a link but for the right mouse button. The rationale is that modern buttonless trackpads such as Macbook trackpads offer ample gesture support for browsing the web without needing a keyboard, however there is no way to conveniently open links in new tabs. Since I don't use a mouse, this is very convenient.

Do you have any suggestions for a better description?

**Comment by ilyaigpetrov** [comment]
"A Google Chrome extension that makes right clicking on links open them in a new background tab. Targeted for keyboardless surfing or for restricted mouses/pads."

**Comment by Etheryte** [comment]
I'm not sure if that's really accurate since that doesn't actually say anything new about what the extension does, only who it's targeted towards — which isn't really true, since it can be used by anyone. Similarly I wouldn't call those devices restricted as in many ways they can do a lot more with gestures than a regular mouse can.

Regardless, thanks a lot for your input, I'll let the idea sit for a bit and update the readme if I come up with a better description.
